controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
account_insurance:
    resource: '../src/Controller/Account/InsuranceController.php'
    type: attribute
